schemaVersion: "2.0.0"

containerRunOptions:
  user: "user"
  privileged: false

commandTests:
  - name: "Check node version"
    command: "node"
    args: ["--version"]
    expectedOutput: [".*25.2.1"]
    exitCode: 0
  - name: "Check the default user"
    command: "whoami"
    args: []
    expectedOutput: ["user"]
    exitCode: 0

envVarTests:
  - name: "Check customized environment variables"
    envVars:
      - key: "LOCAL_COMMIT_SHORT"
        present: true

fileExistenceTests:
  - name: "Check the Next.js standalone build"
    path: "/app/.next/standalone"
    shouldExist: true
    permissions: "drwxr-xr-x"
  - name: "Check the Next.js start script"
    path: "/app/server.js"
    shouldExist: true
    permissions: "rwxr-xr-x"

metadataTest:
  workdir: "/app/"
  user: "user"
