failure-threshold: error
format: tty
ignored:
  - DL3004
  - DL3008
  - DL3016
  - DL3049
  - DL3050
label-schema:
  author: text
  contact: email
  title: text
strict-labels: true
trustedRegistries:
  - docker.io
