import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialBasics: [{ type: "autogenerated", dirName: "tutorial-basics" }],
  tutorialExtras: [{ type: "autogenerated", dirName: "tutorial-extras" }],
};

export default sidebars;
