import { ForwardRefExoticComponent, RefAttributes } from "react";
import { Route } from "next";
import {
  SiAmazon,
  SiBabel,
  SiCplusplus,
  SiCss3,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElectron,
  SiExpress,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGnubash,
  SiGo,
  SiGoogle,
  SiGooglechrome,
  SiGooglecloud,
  SiGulp,
  SiHtml5,
  SiIonic,
  SiJavascript,
  SiJson,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNginx,
  SiNpm,
  SiNuget,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiRedux,
  SiSemanticrelease,
  SiTailwindcss,
  SiTerraform,
  SiThreedotjs,
  SiTypescript,
  SiWayland,
  SiWebpack,
} from "@icons-pack/react-simple-icons";
import {
  DatabaseIcon,
  HomeIcon,
  LucideProps,
  NewspaperIcon,
  NotebookIcon,
  UserIcon,
} from "lucide-react";

export const LUCIDE_ICON = {
  DatabaseIcon,
  HomeIcon,
  NewspaperIcon,
  NotebookIcon,
  UserIcon,
} as const;

export const ROUTE_ICON: Readonly<
  Record<
    Route,
    ForwardRefExoticComponent<
      Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>
    >
  >
> = {
  "/": HomeIcon,
  "/blog": NewspaperIcon,
  "/profile": UserIcon,
} as const;

export const TECHNOLOGY_ICON = {
  ".NET": SiDotnet,
  "C++": SiCplusplus,
  "Express.js": SiExpress,
  "Next.js": SiNextdotjs,
  "Protocol Buffers": SiGoogle,
  "React.js": SiReact,
  "Tailwind CSS": SiTailwindcss,
  "Three.js": SiThreedotjs,
  AWS: SiAmazon,
  Babel: SiBabel,
  Bash: SiGnubash,
  CSS: SiCss3,
  Django: SiDjango,
  Docker: SiDocker,
  Electron: SiElectron,
  Firebase: SiFirebase,
  Flask: SiFlask,
  GCP: SiGooglecloud,
  Git: SiGit,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Go: SiGo,
  gRPC: SiGoogle,
  Gulp: SiGulp,
  HTML: SiHtml5,
  Ionic: SiIonic,
  JavaScript: SiJavascript,
  JSON: SiJson,
  Kubernetes: SiKubernetes,
  Linux: SiLinux,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  Nginx: SiNginx,
  NPM: SiNpm,
  NuGet: SiNuget,
  Python: SiPython,
  RabbitMQ: SiRabbitmq,
  Redis: SiRedis,
  Redux: SiRedux,
  SemanticRelease: SiSemanticrelease,
  Terraform: SiTerraform,
  TypeScript: SiTypescript,
  Wayland: SiWayland,
  WebKit: SiGooglechrome,
  Webpack: SiWebpack,
  SQL: DatabaseIcon,
  Supervisord: NotebookIcon,
} as const;
