import { ForwardRefExoticComponent, RefAttributes } from "react";
import { Route } from "next";
import {
  SiAmazon,
  SiBabel,
  SiCplusplus,
  SiCss3,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElectron,
  SiExpress,
  SiFlask,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGnubash,
  SiGooglechrome,
  SiGooglecloud,
  SiGulp,
  SiHtml5,
  SiJavascript,
  SiJson,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNginx,
  SiNuget,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiRedux,
  SiTailwindcss,
  SiTerraform,
  SiThreedotjs,
  SiTypescript,
  SiWebpack,
  SiGo,
  SiNextdotjs,
} from "@icons-pack/react-simple-icons";
import {
  HomeIcon,
  LucideProps,
  NewspaperIcon,
  PersonStandingIcon,
} from "lucide-react";

export const ROUTE_ICON: Readonly<
  Record<
    Route,
    ForwardRefExoticComponent<
      Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>
    >
  >
> = {
  "/": HomeIcon,
  "/blog": NewspaperIcon,
  "/profile": PersonStandingIcon,
} as const;

export const TECHNOLOGY_ICON = {
  ".NET": SiDotnet,
  "C++": SiCplusplus,
  "Express.js": SiExpress,
  "Next.js": SiNextdotjs,
  "React.js": SiReact,
  "Tailwind CSS": SiTailwindcss,
  "Three.js": SiThreedotjs,
  AWS: SiAmazon,
  Babel: SiBabel,
  Bash: SiGnubash,
  CSS: SiCss3,
  Django: SiDjango,
  Docker: SiDocker,
  Electron: SiElectron,
  Flask: SiFlask,
  GCP: SiGooglecloud,
  Git: SiGit,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Go: SiGo,
  Gulp: SiGulp,
  HTML: SiHtml5,
  JavaScript: SiJavascript,
  JSON: SiJson,
  Kubernetes: SiKubernetes,
  Linux: SiLinux,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  Nginx: SiNginx,
  NuGet: SiNuget,
  Python: SiPython,
  RabbitMQ: SiRabbitmq,
  Redis: SiRedis,
  Redux: SiRedux,
  Terraform: SiTerraform,
  TypeScript: SiTypescript,
  WebKit: SiGooglechrome,
  Webpack: SiWebpack,
} as const;
