import * as next from "next";
import {
  SiAmazon,
  SiBabel,
  SiCplusplus,
  SiCss3,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElectron,
  SiExpress,
  SiFlask,
  SiGithub,
  SiGitlab,
  SiGnubash,
  SiGooglechrome,
  SiGooglecloud,
  SiGulp,
  SiHtml5,
  SiJavascript,
  SiJson,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNginx,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiRedux,
  SiTailwindcss,
  SiTerraform,
  SiThreedotjs,
  SiTypescript,
  SiWebpack,
} from "react-icons/si";

export const site = {
  name: "Jin Yu Zhang's Website",
  article: {
    path: "public/article",
  },
  iconMap: {
    ".NET": SiDotnet,
    "C++": SiCplusplus,
    "Express.js": SiExpress,
    "React.js": SiReact,
    "Tailwind CSS": SiTailwindcss,
    "Three.js": SiThreedotjs,
    AWS: SiAmazon,
    Babel: SiBabel,
    Bash: SiGnubash,
    CSS: SiCss3,
    Django: SiDjango,
    Docker: SiDocker,
    Electron: SiElectron,
    Flask: SiFlask,
    GCP: SiGooglecloud,
    GitHub: SiGithub,
    GitLab: SiGitlab,
    Gulp: SiGulp,
    HTML: SiHtml5,
    JavaScript: SiJavascript,
    JSON: SiJson,
    Kubernetes: SiKubernetes,
    Linux: SiLinux,
    MongoDB: SiMongodb,
    MySQL: SiMysql,
    Nginx: SiNginx,
    Python: SiPython,
    RabbitMQ: SiRabbitmq,
    Redis: SiRedis,
    Redux: SiRedux,
    Terraform: SiTerraform,
    TypeScript: SiTypescript,
    WebKit: SiGooglechrome,
    Webpack: SiWebpack,
  },
};

export const home = {
  summary: [
    { title: "DevOps", portion: 1.5 },
    { title: "System Design", portion: 2 },
    { title: "Leadership", portion: 1.5 },
    { title: "Front-End", portion: 4 },
    { title: "Back-End", portion: 4.5 },
  ],
  experience: [
    {
      title: "Software Engineer at Shopee",
      time: "Jan 2022 - Feb 2022",
    },
    {
      title: "Software Engineer at StageSource",
      time: "Sep 2022 - Dec 2022",
    },
    {
      title: "Master in Computer Science at Boston University",
      time: "May 2022 - Jan 2024",
    },
    {
      title: "Software Engineering Intern at CooperSurgical",
      time: "May 2023 - Aug 2023",
    },
    {
      title:
        "Certificate in Data Science and Machine Learning at Massachusetts Institute of Technology",
      time: "Aug 2023 - Nov 2023",
    },
    {
      title: "Software Engineer at CooperSurgical",
      time: "Jan 2024 - Present",
    },
  ],
  skill: [
    [
      { name: "Python", icon: site.iconMap.Python },
      { name: "TypeScript", icon: site.iconMap.TypeScript },
      { name: "JavaScript", icon: site.iconMap.JavaScript },
      { name: "Bash", icon: site.iconMap.Bash },
      { name: "C++", icon: site.iconMap["C++"] },
      { name: ".NET", icon: site.iconMap[".NET"] },
    ],
    [
      { name: "Docker", icon: site.iconMap.Docker },
      { name: "AWS", icon: site.iconMap.AWS },
      { name: "GCP", icon: site.iconMap.GCP },
      { name: "GitHub", icon: site.iconMap.GitHub },
      { name: "GitLab", icon: site.iconMap.GitLab },
      { name: "Linux", icon: site.iconMap.Linux },
      { name: "Kubernetes", icon: site.iconMap.Kubernetes },
    ],
    [
      { name: "MongoDB", icon: site.iconMap.MongoDB },
      { name: "MySQL", icon: site.iconMap.MySQL },
      { name: "Redis", icon: site.iconMap.Redis },
      { name: "RabbitMQ", icon: site.iconMap.RabbitMQ },
      { name: "Nginx", icon: site.iconMap.Nginx },
      { name: "Terraform", icon: site.iconMap.Terraform },
    ],
    [
      { name: "Express.js", icon: site.iconMap["Express.js"] },
      { name: "Flask", icon: site.iconMap.Flask },
      { name: "Django", icon: site.iconMap.Django },
    ],
    [
      { name: "React.js", icon: site.iconMap["React.js"] },
      { name: "Tailwind CSS", icon: site.iconMap["Tailwind CSS"] },
      { name: "Three.js", icon: site.iconMap["Three.js"] },
      { name: "Electron", icon: site.iconMap["Electron"] },
      { name: "Redux", icon: site.iconMap["Redux"] },
      { name: "HTML", icon: site.iconMap.HTML },
      { name: "CSS", icon: site.iconMap.CSS },
      { name: "Webpack", icon: site.iconMap.Webpack },
      { name: "Gulp", icon: site.iconMap.Gulp },
      { name: "Babel", icon: site.iconMap.Babel },
    ],
  ],
  project: [
    {
      title: "A.I. Story Writer",
      description:
        "A web application that generates stories using OpenAI's GPT-3.5-turbo model.",
      href: "/project",
    },
    {
      title: "Dynamic Account Hub",
      description:
        "A web application that allows users to manage their accounts and settings.",
      href: "/project",
    },
    {
      title: "Cryptography CLI",
      description:
        "A command-line interface for encrypting and decrypting files using various algorithms.",
      href: "/project",
    },
  ] as { title: string; description: string; href: next.Route }[],
};
